### PR TITLE
Gracefully don't process LimitedLayer objects for a Detailed Trace

### LINKED ISSUE #267: scout_apm 2.5.0 raise error in development
[`LimitedLayer`](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/limited_layer.rb) seems to be lacking some methods called by [LayerConverters::TraceConverter#create_spans](
https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/layer_converters/trace_converter.rb#L89-L90)

#### Stacktrace
```
Exception NoMethodError in Rack application object (undefined method `start_time' for #<ScoutApm::LimitedLayer:0x00007fee1b3b1b20>) (process 35747, thread 0x00007fedfd062f78(Worker 1)):
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:89:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:67:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:66:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:66:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:61:in `block (2 levels) in each'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:60:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:61:in `block (2 levels) in each'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:60:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:61:in `block (2 levels) in each'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:60:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:60:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/slow_request_converter.rb:95:in `span_trace'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/slow_request_converter.rb:56:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/scored_item_set.rb:81:in `store!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/scored_item_set.rb:62:in `<<'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:259:in `block in merge_slow_transactions!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:258:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:258:in `merge_slow_transactions!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:66:in `block in track_slow_transaction!'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:65:in `track_slow_transaction!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/slow_request_converter.rb:13:in `record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:312:in `block in record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:311:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:311:in `inject'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:311:in `record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/synchronous_recorder.rb:27:in `record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:216:in `stop_request'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:124:in `stop_layer'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/instruments/middleware_summary.rb:60:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

### PR DESCRIPTION
**Pull request by itsderek23**
Fixes #267 by not processing limited layers.

Note that the exception reported in #267 only hits this issue if `DEFAULT_UNIQUE_CUTOFF` > `MAX_SPANS`. This provides additional protection. 

This is phase 2 mentioned in Slack:

image

### CODE REVIEW

File: lib/scout_apm/layer_converters/trace_converter.rb [hunk 1]
```diff
@@ -117,7 +117,9 @@ def create_spans(layer, parent_id = nil)
           tags)
 
         layer.children.each do |child|
-          unless over_span_limit?(result)
+          # Don't create spans from limited layers. These don't have start/stop times and our processing can't
+          # handle these yet.
+          unless over_span_limit?(result) or child.is_a?(LimitedLayer)
```
Comment (PikachuEXE) [inline lib/scout_apm/layer_converters/trace_converter.rb]: Why use `or` instead of `||`

Comment (itsderek23) [reply lib/scout_apm/layer_converters/trace_converter.rb]: Yep - good catch! Not control flow. Updated!
